name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Generate Snake Animation - Dark
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: fufuizm
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#58a6ff&color_dots=#0d1117,#0e4429,#006d32,#26a641,#39d353

      - name: Generate Snake Animation - Light
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: fufuizm
          outputs: |
            dist/github-snake.svg?palette=github&color_snake=#24292f&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39

      - name: Generate Snake Animation - Ocean
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: fufuizm
          outputs: |
            dist/github-snake-ocean.svg?palette=github-dark&color_snake=#79c0ff&color_dots=#0d1117,#0a3069,#0550ae,#0969da,#218bff

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
